// Generated by CoffeeScript 1.7.1
(function() {
  (function() {
    "use strict";
    var CarrerData, root;
    CarrerData = function() {
      var items, lanes;
      items = [
        {
          "class": "past",
          desc: "This is a description.",
          end: new Date(2014, 5, 25),
          id: 0,
          lane: 0,
          start: new Date(2013, 5, 25)
        }, {
          "class": "past",
          desc: "This is a description.",
          end: new Date(2014, 5, 25),
          id: 1,
          lane: 1,
          start: new Date(2013, 5, 25)
        }, {
          "class": "past",
          desc: "This is a description.",
          end: new Date(2014, 5, 25),
          id: 2,
          lane: 2,
          start: new Date(2013, 5, 25)
        }, {
          "class": "past",
          desc: "This is a description.",
          end: new Date(2014, 5, 25),
          id: 3,
          lane: 3,
          start: new Date(2013, 5, 25)
        }, {
          "class": "past",
          desc: "This is a description.",
          end: new Date(2014, 1, 25),
          id: 4,
          lane: 4,
          start: new Date(2013, 5, 25)
        }
      ];
      lanes = [
        {
          id: 0,
          label: 'lane 0'
        }, {
          id: 1,
          label: 'lane 1'
        }, {
          id: 2,
          label: 'lane 2'
        }, {
          id: 3,
          label: 'lane 3'
        }, {
          id: 4,
          label: 'lane 4'
        }
      ];
      return {
        items: items,
        lanes: lanes
      };
    };
    root = (typeof exports !== "undefined" && exports !== null ? exports : window);
    return root.carrerData = CarrerData;
  }).call(this);

}).call(this);
